### ISSUE TITLE
Broken on plasma 5.22

### ISSUE THREAD

**Issue by mrhll** [KSmanis/kwin-move-window-to-center#5]
Hi and thank you for this big extension, a must have for me but unfortunately this has been broken on plasma 5.22 and windows no more moving to center.

**Comment by Sojiro84** [comment]
I can confirm it doesn't work anymore on 5.22.

**Comment by KSmanis** [comment]
Thank you both for the feedback. I will most probably get on it once Plasma 5.22 is released; until then PRs are most welcome.

**Comment by KSmanis** [comment]
I'm on Gentoo, kwin_x11 5.22.0, and I do not seem to be affected by this issue. Could you share more details about your environment?

**Comment by mrhll** [comment]
I confirm it is working again on the official 5.22 release on arch. The problem occured on beta but now all is ok. Thank you for beeing involved.

**Comment by Sojiro84** [comment]
> I confirm it is working again on the official 5.22 release on arch. The problem occured on beta but now all is ok. Thank you for beeing involved.

It works again indeed!

It's a shame the original KDE centering does not have a option to account for the panel size/placement.

Thank you for this script.
