### ISSUE TITLE
Where to learn more about JS KDE Plasma API?

### ISSUE THREAD

**Issue by ghxstweb** [KSmanis/kwin-move-window-to-center#8]
Hi @KSmanis, hope you have been well. Thanks for making a simple javascript app using the KDE API! I wanted to ask where someone might learn more about making JS apps within the KDE ecosystem? How would I make a widget, for example, with a UI and clickable regions? 

Thanks in advance for your time!

**Comment by KSmanis** [comment]
[KWin scripting tutorial](https://develop.kde.org/docs/plasma/kwin/)
[KWin scripting API](https://develop.kde.org/docs/plasma/kwin/api/)

Also take a look at existing KWin scripts shipped with KDE or on the [KDE store](https://store.kde.org/browse?cat=210).
